site_name: TeSLA CE Client
site_url: https://tesla-ce.github.io/python-client/
site_author: Xavier Baro

nav:
    - Home: index.md
    - Client: client.md

theme:
  name: "material"
  custom_dir: overrides

markdown_extensions:
  - admonition
watch:
  - src/tesla_ce_client
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          load_external_modules: true
          allow_inspection: true
          options:
            rendering:
              show_source: true
            selection:
              docstring_style: sphinx
extra:
  version:
    provider: mike

