site_name: TeSLA CE Client
nav:
    - Home: index.md

theme:
  name: "material"

markdown_extensions:
  - admonition

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.insert(0, "src")
            - print('INITIALIZED')
          rendering:
            show_source: true
          selection:
            docstring_style: restructured-text
      watch:
        - src/tesla_ce_client
extra:
  version:
    provider: mike

